apiVersion: v1
kind: Pod
metadata:
  labels:
    name: springboot
  name: spring-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
      - image: dockerhandson/spring-boot-mongo
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080
